ifndef::imagesdir[:imagesdir: ../../../../../../imgs/]
ifndef::listdir[:listdir: ../../../../../../../../examples/java/src/main/java/kovteba/collectionframework/iterable/collection/list]
ifndef::listtestdir[:listtestdir: ../../../../../../../../examples/java/src/main/java/kovteba/collectionframework/iterable/collection/list]

[#java-collection-framework-list]
===== List
Інтерфейс `List` являє собою колекцію, в якій можливі дублікати значень. Елементи такої колекції пронумеровані, починаючи від нуля, до них можна звертатися по індексу. Розширяє `Collection` і визначає методи для роботи зі списками.

[source,subs="normal"]
----
[I] <<java-collection-framework-list-interface,List<E>>>
└── [A] AbstractList<E>
    ├── [A] AbstractSequentialList<E>
    │   └── [C] <<java-collection-framework-linkedlist,LinkedList<E>>>
    ├── [C] <<java-collection-framework-arraylist,ArrayList<E>>>
    ├── [L] <<java-collection-framework-vector,Vector<E>>>
    │   └── [L] <<java-collection-framework-stack,Stack<E>>>
    └── [CC] CopyOnWriteArrayList<E>
----

.Методи інтерфейсу `List`:

- `void add(int index, E obj)` — додає в список по індексу `index` об'єкт `obj`;
- `boolean addAll(int index, Collection<? extends E> col)` — додає в список по індексу `index` всі елементи колекції `col`. Якщо в результаті додавання список був змінений, то повертається `true`, інакше повертається `false`;
- `E get(int index)` — повертає об'єкт зі списку по індексу `index`;
- `int indexOf(Object obj)` — повертає індекс першого входження об'єкта `obj` в список. Якщо об'єкт не знайдений, то повертається `-1`;
- `int lastIndexOf(Object obj)` — повертає індекс останнього входження об'єкта `obj` в список. Якщо об'єкт не знайдений, то повертається `-1`;
- `ListIterator<E> listIterator()` — повертає об'єкт `ListIterator` для обходу елементів списку;
- `static <E> List<E> of(елементи)` — створює з набору елементів об'єкт `List`;
- `E remove(int index)` — видаляє об'єкт зі списку по індексу `index`, повертаючи при цьому видалений об'єкт;
- `E set(int index, E obj)` — присвоює значення об'єкта `obj` елементу, який знаходиться по індексу `index`;
- `void sort(Comparator<? super E> comp)` — сортує список за допомогою компаратора `comp`;
- `List<E> subList(int start, int end)` — отримує набір елементів, які знаходяться в списку між індексами `start` і `end`.

include::arraylist/collection-framework-class-arraylist.adoc[]
include::linkedlist/collection-framework-class-linkedlist.adoc[]
include::vector/stack/collection-framework-class-stack.adoc[]
include::vector/collection-framework-class-vector.adoc[]
include::copyonwritearraylist/collection-framework-class-copyonwritearraylist.adoc[]

include::collection-framework-interface-list-vs-linkedlist.adoc[]
